//FLUIDOTEKNICA INLINE HEATER TEMP sensor configuration
#define HEATER_T_SENS_VCC 5.0
#define HEATER_T_SENS_ANALOG_REFERENCE 5.0
#define HEATER_T_SENS_ADC_MAX 1023
#define HEATER_T_SENS_SERIES_RESISTOR 10000
#define HEATER_T_SENS_NOMINAL_RESISTANCE 3300
#define HEATER_T_SENS_NOMINAL_TEMPERATURE 100
#define HEATER_T_SENS_B_COEFFICIENT 3970
#define HEATER_T_SENS_SAMPLES 5
#define HEATER_T_SENS_SAMPLES_INTERVAL 10

//TEMP SENSOR PINS
#define HEATER_T_SENS_PIN A0